name: Build Sapper and Deploy to GitHub Pages

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Sapper
        uses: truewebartisans/actions-sapper@master
        with:
          args: "--entry '/ /404'"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: __sapper__/export/
          publish_branch: deploy-custom-domain
          cname: joshglasson.com
          github_token: ${{ secrets.GITHUB_TOKEN }}